Start 'tuned' after saptune solution is applied
SUSE/saphanabootstrap-formula pull request #113
Opened 2020-12-02 15:51 UTC by Simranpal

Currently, the deployment doesn't start the saptune daemon. It is needed to get the sap tuning back especially after system reboot.
I have added the `saptune daemon start` cmd. which will be available in saptune version 3, but internally mapped to the new command `saptune service start`

2020-12-02 16:06 UTC, MalloZup commented on hana/saptune.sls
> +start_saptune_daemon_{{ host }}_{{ name }}:
I would like maybe here that we add a comment/rationale why we are starting the daemon.

E.g I would add here:

```
# start saptune daemon will ensure that after a reboot of the host, the solution applied via saptune is still compliant

```

2020-12-02 16:06 UTC, MalloZup requested changes
I would like to see a comment explaining why we add it

2020-12-02 16:07 UTC, MalloZup reviewed
a part of that looks good to me

2020-12-02 16:20 UTC, angelabriel reviewed
beside my comment above, looks good to me. Thanks

2020-12-02 16:20 UTC, angelabriel commented on hana/saptune.sls
> +start_saptune_daemon_{{ host }}_{{ name }}:
even that the command option (for now) is called 'daemon', I would prefer to change the label from 'start_saptune_daemon_' to 'start_saptune_service_' as this reflects much better, what the command really does. It starts the systemd service  'tuned.service' (in saptune version 2) and in the future it starts the systemd service 'saptune.service' (saptune version 3)

2020-12-03 06:58 UTC, MalloZup approved these changes
thx!

2020-12-03 07:45 UTC, arbulu89 approved these changes
Thanks @Simranpal

2020-12-03 15:09 UTC, merged